---

- name: REMOVE DEVICES FROM FGT GRP
  hosts: FortiManager
  connection: httpapi
  gather_facts: False

  tasks:
    - name: REMOVE DEVICES FROM DEVICE GROUP
      fmgr_device_group:
        #GETTING FORTIMANAGER HOST IP OR NAME FROM ANSIBLE INVENTORY FOR HOSTS GROUP ABOVE
        #DYNAMIC MAPPING FOR THE FORTIMANAGER LOGIN AS SPECIFIED IN INVENTORY FILE
        #STATE if "present" ADD THE GROUP MEMBERS, IF "absent" DELETE THE GROUP MEMBERS
        mode: "delete"
        #GROUP NAME TO REMOVE THE DEVICES FROM
        grp_name: "testtest"
        #FRIENDLY NAME OF DEVICES IN FORTIMANAGER YOU WISH TO DELETE FROM THE GROUP
        #MULTIPLE DEVICES CAN BE SPECIFIED BY COMMA SEPARATION (CSV)
        grp_members: "FGT3"
        #ADOM YOU WISH TO ADD
        adom: "ansible"

    - name: REMOVE DEVICES FROM DEVICE GROUP2
      fmgr_device_group:
        mode: "delete"
        grp_name: "TestGroup"
        grp_members: "FGT1"
        adom: "ansible"
