---

- name: CREATE FGT GRP
  hosts: FortiManager
  connection: httpapi
  gather_facts: False

  tasks:

  - name: ADD DEVICES TO DEVICE GROUP
    fmgr_device_group:
      #GETTING FORTIMANAGER HOST IP OR NAME FROM ANSIBLE INVENTORY FOR HOSTS GROUP ABOVE
      #DYNAMIC MAPPING FOR THE FORTIMANAGER LOGIN AS SPECIFIED IN INVENTORY FILE
      #STATE if "present" ADD THE GROUP MEMBERS, IF "absent" DELETE THE GROUP MEMBERS
      mode: "add"
      #GROUP NAME TO ADD THE DEVICES TO
      grp_name: "TestGroup"
      #FRIENDLY NAME OF DEVICES IN FORTIMANAGER YOU WISH TO ADD TO THE GROUP
      #MULTIPLE DEVICES CAN BE SPECIFIED BY COMMA SEPARATION (CSV)
      grp_members: "FGT1"
      #ADOM TO CREATE THE GROUP IN
      adom: "ansible"
      vdom: "root"

  - name: ADD DEVICES TO DEVICE GROUP 2
    fmgr_device_group:
      mode: "add"
      grp_name: "testtest"
      grp_members: "FGT3"
      adom: "ansible"
      vdom: "root"
