---

- name: CONFIG FMGR FIREWALL OBJECTS
  hosts: FortiManager
  connection: httpapi
  gather_facts: False

  tasks:

  - name: ADD IPv4 IP ADDRESS FQDN OBJECT
    fmgr_fwobj_address:
      ipv4: "fqdn"
      mode: "add"
      adom: "ansible"
      fqdn: "bluesnews.com"
      name: "Bluesnews"
      comment: "Dev Example for Ansible"
      color: "22"
      #tags: "ansible, ipv4, test123, test321"
