---
- name: DISCOVER AND ADD DEVICES
  hosts: FortiManager
  connection: httpapi
  gather_facts: False

  tasks:
    - name: DISCOVER AND ADD DEVICE FGT4
      fmgr_device:
        adom: "ansible"
        #DEVICE LOGIN
        device_username: "admin"
        device_password: "fortinet"
        #DEVICE IP ADDRESS
        device_ip: "10.7.220.164"
        #FRIENDLY NAME FOR DEVICE IN FORTIMANAGER
        device_unique_name: "FGT4"
    - name: DISCOVER AND ADD DEVICE FGT5
      fmgr_device:
        adom: "ansible"
        device_username: "admin"
        device_password: "fortinet"
        device_ip: "10.7.220.165"
        device_unique_name: "FGT5"
    - name: DISCOVER AND ADD DEVICE FGT6
      fmgr_device:
        adom: "ansible"
        device_username: "admin"
        device_password: "fortinet"
        device_ip: "10.7.220.166"
        device_unique_name: "FGT6"
    - name: DISCOVER AND ADD DEVICE FGT1
      fmgr_device:
        adom: "ansible"
        #DEVICE LOGIN
        device_username: "admin"
        device_password: "fortinet"
        #DEVICE IP ADDRESS
        device_ip: "10.7.220.151"
        #FRIENDLY NAME FOR DEVICE IN FORTIMANAGER
        device_unique_name: "FGT1"
    - name: DISCOVER AND ADD DEVICE FGT2
      fmgr_device:
        adom: "ansible"
        device_username: "admin"
        device_password: "fortinet"
        device_ip: "10.7.220.152"
        device_unique_name: "FGT2"
    - name: DISCOVER AND ADD DEVICE FGT3
      fmgr_device:
        adom: "ansible"
        device_username: "admin"
        device_password: "fortinet"
        device_ip: "10.7.220.153"
        device_unique_name: "FGT3"