---
- name: SET FORTIMANAGER HA MODE TO SLAVE
  hosts: FortiManagerSlave
  connection: httpapi
  gather_facts: False

  tasks:
    - name: SET FORTIMANAGER HA NODE TO SLAVE
      fmgr_ha:
        fmgr_ha_mode: "slave"
        fmgr_ha_cluster_pw: "fortinet"
        fmgr_ha_cluster_id: "2"