---

- name: CONFIG FW POLICIES
  hosts: FortiManager
  connection: httpapi
  gather_facts: False

  tasks:

  - name: ADD VERY BASIC IPV4 POLICY WITH NO NAT (WIDE OPEN)
    fmgr_fwpol_ipv4:
      mode: "delete"
      adom: "ansible"
      package_name: "default"
      name: "Basic_IPv4_Policy"


  - name: ADD VERY BASIC IPV4 POLICY WITH NAT AND MULTIPLE ENTRIES
    fmgr_fwpol_ipv4:
      mode: "delete"
      adom: "ansible"
      package_name: "default"
      name: "Basic_IPv4_Policy_2"

#  - name: ADD VERY BASIC IPV4 POLICY WITH NAT AND MULTIPLE ENTRIES
#    fmgr_fwpol_ipv4:
#      mode: "delete"
#      adom: "ansible"
#      package_name: "default"
#      name: "Basic_IPv4_Policy_3"
