---

- name: CONFIG FMGR FIREWALL OBJECTS
  hosts: FortiManager
  connection: httpapi
  gather_facts: False

  tasks:
    - name: ADD FMGR_FIREWALL_IPPOOL Overload
      fmgr_fwobj_ippool:
        mode: "add"
        adom: "ansible"
        name: "Ansible_pool4_overload"
        comments: "Created by ansible"
        type: "overload"

        # OPTIONS FOR ALL MODES
        startip: "10.10.10.10"
        endip: "10.10.10.100"
        arp_reply: "enable"

      # FIXED PORT RANGE OPTIONS
#       source_startip:
#       source_endip:

      # PORT BLOCK ALLOCATION OPTIONS
#       block_size:
#       num_blocks_per_user:

      # ADVANCED OPTIONS
#       pba_timeout:
#       associated_interface:
#       permit_any_host:
#       arp_intf:

      # DYNAMIC "PER-DEVICE" MAPPING OPTIONS
#       dynamic_mapping_arp_intf:
#       dynamic_mapping_arp_reply:
#       dynamic_mapping_associated_interface:
#       dynamic_mapping_block_size:
#       dynamic_mapping_comments:
#       dynamic_mapping_endip:
#       dynamic_mapping_num_blocks_per_user:
#       dynamic_mapping_pba_timeout:
#       dynamic_mapping_permit_any_host:
#       dynamic_mapping_source_endip:
#       dynamic_mapping_source_startip:
#       dynamic_mapping_startip:
#       dynamic_mapping_type:


    - name: ADD FMGR_FIREWALL_IPPOOL one-to-one
      fmgr_fwobj_ippool:
        mode: "add"
        adom: "ansible"
        name: "Ansible_pool4_121"
        comments: "Created by ansible"
        type: "one-to-one"

        # OPTIONS FOR ALL MODES
        startip: "10.10.20.10"
        endip: "10.10.20.100"
        arp_reply: "enable"

    - name: ADD FMGR_FIREWALL_IPPOOL FIXED PORT RANGE
      fmgr_fwobj_ippool:
        mode: "add"
        adom: "ansible"
        name: "Ansible_pool4_fixed_port"
        comments: "Created by ansible"
        type: "fixed-port-range"

        # OPTIONS FOR ALL MODES
        startip: "10.10.40.10"
        endip: "10.10.40.100"
        arp_reply: "enable"
        # FIXED PORT RANGE OPTIONS
        source_startip: "192.168.20.1"
        source_endip: "192.168.20.20"

    - name: ADD FMGR_FIREWALL_IPPOOL PORT BLOCK ALLOCATION
      fmgr_fwobj_ippool:
        mode: "add"
        adom: "ansible"
        name: "Ansible_pool4_port_block_allocation"
        comments: "Created by ansible"
        type: "port-block-allocation"

        # OPTIONS FOR ALL MODES
        startip: "10.10.30.10"
        endip: "10.10.30.100"
        arp_reply: "enable"
        # PORT BLOCK ALLOCATION OPTIONS
        block_size: "128"
        num_blocks_per_user: "1"