---

- name: CONFIG FW POLICY PACKAGES AND FOLDERS
  hosts: FortiManager
  connection: httpapi
  gather_facts: False

  tasks:
  - name: INSTALL PACKAGE
    fmgr_fwpol_package:
      mode: "set"
      adom: "ansible"
      name: "ansibleTestPackage1"
      object_type: "install"
      scope_members: "FGT6"
      scope_members_vdom: "ansible1"


