---

- name: CONFIG FGT HOSTNAME AND INTERFACE
  hosts: FortiManager
  connection: httpapi
  gather_facts: False

  tasks:

  - name: CHANGE HOSTNAME
    fmgr_device_config:
      device_hostname: "ansible-fgt01"
      device_unique_name: "FGT1"
      adom: "ansible"


  - name: EDIT INTERFACE INFORMATION
    fmgr_device_config:
      adom: "ansible"
      device_unique_name: "FGT1"
      interface: "port2"
      interface_ip: "10.1.1.1/24"
      interface_allow_access: "ping, telnet, https, http"
