---
- name: DISCOVER AND ADD DEVICES
  hosts: FortiManager
  connection: httpapi
  gather_facts: False

  tasks:
    - name: CHANGE HOSTNAME
      fmgr_device_config:
        device_hostname: "ChangedbyAnsible"
        device_unique_name: "FGT1"

    - name: EDIT INTERFACE INFORMATION
      fmgr_device_config:
        adom: "root"
        device_unique_name: "FGT2"
        interface: "port3"
        interface_ip: "10.255.1.1/24"
        interface_allow_access: "ping, telnet, https, http"
