---
- name: Create and Delete security profile in FMG
  hosts: FortiManager
  connection: httpapi
  gather_facts: False

  tasks:

  - name: DELETE Profile
    fmgr_secprof_appctrl:
      name: "Ansible_Application_Control_Profile"
      comment: "Created by Ansible Module TEST"
      adom: "ansible"
      mode: "delete"

  - name: CREATE Profile
    fmgr_secprof_appctrl:
      name: "Ansible_Application_Control_Profile"
      comment: "Created by Ansible Module TEST"
      adom: "ansible"
      mode: "set"
      entries: [{
                action: "block",
                log: "enable",
                log-packet: "enable",
                protocols: ["1"],
                quarantine: "attacker",
                quarantine-log: "enable",
                },
                {action: "pass",
                category: ["2","3","4"]},
              ]

  - name: DELETE Profile 2
    fmgr_secprof_appctrl:
      name: "Ansible_Application_Ctl_Profile2"
      comment: "Created by Ansible Module TEST"
      adom: "ansible"
      mode: "delete"

  - name: CREATE Profile 2
    fmgr_secprof_appctrl:
      name: "Ansible_Application_Ctl_Profile2"
      comment: "Created by Ansible Module TEST"
      adom: "ansible"
      mode: "set"
      entries_action: "pass"
      entries_log: "enable"
      entries_log_packet: "enable"
      entries_protocols: ["1"]
      entries_quarantine: "attacker"
      entries_quarantine_log: "enable"



